version: '2'

services:
  wealthy_ui:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/ui/Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/app/wealthy_api/wealth-service/django_static
      - ./docker/nginx/development:/etc/nginx/conf.d
    environment:
      NODE_OPTIONS: "--max_old_space_size=18192"
    depends_on:
      - wealthy_api
  wealthy_api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    entrypoint: ./docker/api/process_runner.sh
    volumes:
      - static_volume:/app/wealthy_api/wealth-service/django_static
    expose:
      - 8000
      - 27017

volumes:
  static_volume: {}