# Generated by Django 2.2.3 on 2020-07-16 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar'), ('PLN', 'Zloty')], default='PLN', editable=False, max_length=3)),
                ('bought_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='PLN', max_digits=10)),
                ('date_of_bought', models.DateField()),
                ('name', models.CharField(choices=[('silver999', 'Silver999'), ('silver800', 'Silver800'), ('gold999', 'Gold999'), ('gold585', 'Gold585'), ('gold333', 'Gold333')], default='silver999', max_length=10)),
                ('unit', models.CharField(choices=[('oz', 'ounce'), ('g', 'gram'), ('kg', 'kilogram')], default='oz', max_length=10)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Type some information about this transaction (optional)')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_date', models.DateField()),
                ('my_cash_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar'), ('PLN', 'Zloty')], default='PLN', editable=False, max_length=3)),
                ('my_cash', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='PLN', max_digits=10, null=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
